### ISSUE TITLE
[Feature Request] 表达式计算

### ISSUE THREAD

**Issue by ikws4** [yyh9488/ILRuntime-Rider-Degguer#4]
非常感谢作者开发的这个插件。能满足基本的调试需求，但由于不能计算表达式，像成员变量这些就没办法通过鼠标悬浮查看数值（目前好像只支持查看当前函数栈中的local variables），不是特别方便，作者是否考虑支持一下呢？
![48df76be-339c-41f7-95b2-a25f0b3b5852](https://user-images.githubusercontent.com/47056144/223714680-1785ac55-3595-4d5a-b56c-e3872e7bf120.jpeg)
提前感谢！

**Comment by yyh9488** [comment]
能否提供更具体的写法

**Comment by yyh9488** [comment]
类中的成员变量我记得是可以鼠标悬停的只有断点在协程的时候会有提示不了的问题

**Comment by yyh9488** [comment]
还有一种可能你的rider版本太低，由于适配的工作量，一些新功能只在较新的版本上才有

**Comment by ikws4** [comment]
Rider版本：2022.3.2
插件版本：223.4.1
ILRuntime版本：2.0.2

调试器模式用的是 Attach to ILRuntime 2
![image](https://user-images.githubusercontent.com/47056144/224279850-30202257-6436-4b91-9bc9-9ddcf726f6dc.png)
因为使用 Attach to ILRuntime 4 启动不了debug服务
![image](https://user-images.githubusercontent.com/47056144/224279977-c9657c8f-0aa6-4c0f-b7d8-132676583748.png)
![image](https://user-images.githubusercontent.com/47056144/224279947-d20bd3bc-c0f7-4a96-9483-b96a16ef262d.png)



### 可以在debugger的变量窗口手动展开变量，但没办法通过表达式输出结果
![image](https://user-images.githubusercontent.com/47056144/224272912-a153aab0-c2de-4a57-9c98-3aa9f9457da2.png)
```
  Object reference not set to an instance of an object., reason: System.NullReferenceException: Object reference not set to an instance of an object.
     at MetadataLite.API.MetadataTypeLiteEx.IsVoid(IMetadataTypeLite type)
     at Mono.Debugging.Client.Values.ImmediateFormatter.ImmediateFormat(IValue value, IValuePresentation valuePresentation, IPresentationOptions presentationOptions, CancellationToken cancellationToken, Boolean& error)
     at Mono.Debugging.Client.Values.ImmediateFormatter.Format(IValue value, IStackFrame stackFrame, IPresentationOptions options, CancellationToken cancellationToken, Boolean& error, Int32& newSyntheticsCount)
     at JetBrains.Debugger.Worker.PausedContext.<>c__DisplayClass30_2.<ImmediateEvaluate>b__2(IStackFrame frame)
     at JetBrains.Debugger.Worker.PausedContext.WithFrame[T](Int32 frameId, Func`2 action)
     at JetBrains.Debugger.Worker.PausedContext.<>c__DisplayClass30_1.<ImmediateEvaluate>b__1(CancellationToken token)
     at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](Nullable`1 logWithLevel, String key, String message, Func`1 action, Func`2 report)
     at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](ILogger logger, String key, String message, Func`1 action)
     at JetBrains.Debugger.Worker.IDebugSessionFrontendEx.<>c__DisplayClass1_0`1.<EnqueueTask>b__0()
```


### 支持本地栈变量鼠标悬停
![image](https://user-images.githubusercontent.com/47056144/224274189-6fabdb88-14b4-4f2f-a4a1-51e606028a2c.png)


### 无法悬停预览成员变量
![image](https://user-images.githubusercontent.com/47056144/224275460-47efafd5-b256-40c4-ab13-1dd1bf7a73bc.png)



### 本地栈变量无法通过表达式输出，rider提示该功能未实现
![image](https://user-images.githubusercontent.com/47056144/224275684-52b291a8-e9b2-4efb-9001-06da683f627e.png)


```
  The method or operation is not implemented., reason: System.NotImplementedException: The method or operation is not implemented.
     at ILRuntime.Debugger.Rider.ILRuntimeMetadataLite.ILRuntimeMetadataTypeLite.GetMetadataElementType() in D:\Users\admin\RiderProjects\ilr_rider\resharper-rider-plugin-master\content\src\dotnet\Mono.Debugging.Plugins.ILRuntime\MetadataLite\ILRuntimeMetadataLite\ILRuntimeMetadataTypeLite.cs:line 98
     at Mono.Debugging.Client.Values.ImmediateFormatter.AddBracketsIfNeeded(IValuePresentation valuePresentation)
     at Mono.Debugging.Client.Values.ImmediateFormatter.ImmediateFormat(IValue value, IValuePresentation valuePresentation, IPresentationOptions presentationOptions, CancellationToken cancellationToken, Boolean& error)
     at Mono.Debugging.Client.Values.ImmediateFormatter.Format(IValue value, IStackFrame stackFrame, IPresentationOptions options, CancellationToken cancellationToken, Boolean& error, Int32& newSyntheticsCount)
     at JetBrains.Debugger.Worker.PausedContext.<>c__DisplayClass30_2.<ImmediateEvaluate>b__2(IStackFrame frame)
     at JetBrains.Debugger.Worker.PausedContext.WithFrame[T](Int32 frameId, Func`2 action)
     at JetBrains.Debugger.Worker.PausedContext.<>c__DisplayClass30_1.<ImmediateEvaluate>b__1(CancellationToken token)
     at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](Nullable`1 logWithLevel, String key, String message, Func`1 action, Func`2 report)
     at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](ILogger logger, String key, String message, Func`1 action)
```


### 方法应该不是在协程里面执行的
![image](https://user-images.githubusercontent.com/47056144/224275184-751294c1-3ec3-479d-b98e-7cf7288e0750.png)
![image](https://user-images.githubusercontent.com/47056144/224275218-ad62efe7-fd74-4f98-9581-94441d8da91a.png)

**Comment by yyh9488** [comment]
debugger窗口表达式输出功能确实没有实现
成员变量没有提示应该是bug会在接下来几天修复

**Comment by yyh9488** [comment]
成员变量悬浮的功能bug已经在新的插件版本中修复

**Comment by yyh9488** [comment]
Attach to ILRuntime 4的版本是给ILRuntime2.1.0版本使用

**Comment by yyh9488** [comment]
变量表达式输出功能以加入版本计划预计在4月中旬或5月初发布

**Comment by ikws4** [comment]
非常感谢👍！作者有付款码吗，想捐赠一下。
